### ISSUE TITLE
Comma problem for operators []

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#188]
Comma problem for operators []. 
Example of C code:
```c
#include <stdio.h>
 
int main ( void ) {

	int n[] = {0,2,3,6,7,11,12};
	for(int i = 0 ; i < 6; ){
		printf("n[%d] = %d\n",i,n[i+=2,i]);
	}
	return 0;
}
```
Output:
```
panic: format.Node internal error (106:52: expected ']', found '+=' (and 2 more errors))
```

**Comment by Konstantin8105** [comment]
This is big issue, because for solving we have to explode function `printf`.
On C, it is look like that:
```c
...
	for(int i = 0 ; i < 6; ){
		printf("n[%d] = ",i);
                i += 2;
		printf("%d\n",n[i]);
	}
...
```

**Comment by elliotchance** [comment]
I didn't know the comma operator could be used in that way. Did you find a code example that used it this way?

**Comment by Konstantin8105** [comment]
In according to experiments with C code, this is acceptable by `gcc`.
I **haven`t enough experience** of C code, so I never see anywhere.

**Comment by elliotchance** [comment]
Let's leave this for now as I've never seen this actually used in code and I don't understand its semantics.

**Comment by Konstantin8105** [comment]
In according to test file https://github.com/Konstantin8105/c2go-rating/blob/master/SingleCcode/sieve.c :
```c
...
if (level < NPRIMES)
     primes[level++] = i;
...
```
it is equal:
```c
...
if (level < NPRIMES) {
     primes[level] = i;
     level += 1
}
...
```
Some points of that issue, we have to solve.

**Comment by elliotchance** [comment]
Its actually more complicated than that. The correct solution in Go would be:

```go
if level < NPRIMES {
     primes[func () int { level += 1; return level }] = i;
}
```

Any expressions that mutates a variable in an expressions needs to stay in place otherwise if you had:

```c
primes[--level] = level + level++;
```

The right side needs to be evaluated first (I think) then the left side. It would be very tricky to determine the exact order of operators (sometimes impossible) when there is more than one mutation.

Even if there is only one mutation that same expression could be used before or after the mutation and would therefore have the wrong value.

In your specific case of `primes[level++] = i;` there could be a precise optimisation that outputs the code you suggest but this would only come after we can make the increment work correctly in all cases.

**Comment by Konstantin8105** [comment]
Done in #615
