### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#290]
In according to tool `go tool trace` for transpiling file `shell.c` from `sqlite`:
![screenshot at 2017-10-30 23 12 24](https://user-images.githubusercontent.com/16690032/32193350-087a2e1c-bdc8-11e7-84bb-c91a281d6139.png)

Now, `c2go` use only one core for transpiling.(on picture more core - it is GC working).

## Problem
Need to add concurrency if possible.

**Comment by Konstantin8105** [comment]
For function `main.convertLinesToNodes` possible.

**Comment by Konstantin8105** [comment]
For regexp : https://github.com/opennota/re2dfa

**Comment by elliotchance** [comment]
This is great information. One of the biggest performance improvements was made by you with caching the regex's. Parallelising `convertLinesToNodes` would be difficult because it builds a tree.

My first thought is that it would have to be a two stage process:

1. The tree is built to a very shallow depth (like max 3 nodes deep).
2. Iterating the leaf nodes and scheduling the rest of the children to be processed on an independent Go routine.

Ideally in a pool since there would be lots of small jobs.

**Comment by Konstantin8105** [comment]
For function `main.readAST` can use `cacheRegexp`

**Comment by Konstantin8105** [comment]
Now, on my laptop:
```
$ time c2go transpile sqlite3.c
real	1m0.523s
user	1m22.988s
sys	0m2.048s
```

**Comment by Konstantin8105** [comment]
Function `main.convertLinesToNodes` easy to parallelize, because it not a tree - it is parsing each element of slice. Now, I check concerrency of that function and time of transpilig going down from 60 sec to 45 sec. Preliminary 25%. 
But function `main.buildTree` is a tree and that function is difficult for parallelization.

**Comment by Konstantin8105** [comment]
After create a parallell covertLinesToNodes:
![after](https://user-images.githubusercontent.com/16690032/32512827-57d9390c-c409-11e7-9838-43a534993eef.png)
