### ISSUE TITLE
Very useful

### ISSUE THREAD

**Issue by joeblew99** [elliotchance/c2go#7]
I reckon this would be useful for machine learning c packages.
They mostly have no other dependencies like file systems or databases but are designed to be called and return results.

For example OCR in tesseract etc.

I am trying to build an OCR system and so this repo might be a good approach for me.

Could you comment on the soundness if my approach ?

**Comment by elliotchance** [comment]
That does sound very interesting. Do you have any examples of this?

**Comment by Konstantin8105** [comment]
May be , this project https://github.com/tesseract-ocr/tesseract

**Comment by joeblew99** [comment]
@elliotchance sorry for late reply.

@Konstantin8105 yes that is definitely one of them. I was using that a month ago, and it woudl have helped to have it in golang.

I got to admit i admire this project, but i am lacking time and so ended up using a code generator that wraps c. This one.
https://github.com/xlab/c-for-go

But i REALLY think that converting c to golang is preferable and a much bigger payoff for complex libs that have lots of logic in them. For thing like graphics drivers like opengl and others its pointless because those will always need a c layer of course.

**Comment by joeblew99** [comment]
One other thing. QT ! I use the golang QT wrapper, and it has a ton of c underneath it.
It would be amazing to have it all in golang except fot the low level graphic drivers.
I guess that brings up a use case where you want to convert 95% of the code to golang, but still have that thin c layer that talking to hardware on the OS for you stay as c ?

**Comment by elliotchance** [comment]
That's a good point you bring up. There would be many libraries that contain parts that cannot be converted to C. Whether that's because they link against other libraries or contain platform dependant code like ASM or kernel specific drivers.

Recent versions of c2go will generate as much as possible in Go (rather than just failing and producing nothing). Once run through a compiler you would run into those errors that could not be converted. You could fix the errors manually (if possible) but then you would have to maintain a messy patch that would probably break often when the new versions of the C code are retranspiled into Go.

We already have a mechanism for mapping and refactoring functions from C to some Go destination: https://github.com/elliotchance/c2go/blob/master/program/function_definition.go#L36-L61

I see people creating their own configuration file within a project in the same format. This would allow much more complex libraries like QT to work as long as someone was willing to put in the effort to either create their own base level functions *or* map the lowest level functions to a C library to keep all of the orchestration and API in Go but the hard work and performance in C.

**Comment by Konstantin8105** [comment]
@elliotchance Are you try transpiling standard library of C ? https://www.gnu.org/software/libc/libc.html

**Comment by elliotchance** [comment]
@Konstantin8105 the stdlib is not something that can be transpiled because they are mostly low-level functions that are provided as a binary. That is why we map low-level functions to Go equivalents with https://github.com/elliotchance/c2go/blob/master/program/function_definition.go#L62

**Comment by Konstantin8105** [comment]
About about : create a option `c2go`  for create C bindings?
Example for generate:
`c2go binding 1.h 2.h 3.h`
output: 
* file in some binding format: `unistd.binding` for easy adding https://github.com/elliotchance/c2go/blob/master/program/function_definition.go#L62
* Go file with binding: `unistd.go`.

Example of using:
`c2go transpile  main.c -binding=unistd.binding`

**Comment by elliotchance** [comment]
This is not a good idea. The files will include the headers they needs and we would only work with those preprocessor mechanics.

**Comment by Konstantin8105** [comment]
I think, I still don't understood. Because it is look like create full implementation of `glibc` for linux and mac.
Could you clarify on 'real' example.
Goal - create implementation for `getopt` from next source:
https://opensource.apple.com/source/Libc/Libc-320/include/unistd.h.auto.html
Golang haven't analog code of that.

**Comment by elliotchance** [comment]
This is a more complicated discussion about how C bindings will work:

1. Header files are not standalone units. A single library can have hundreds of header files.
2. We want to avoid bindings with libraries wherever possible. It makes the programs much slower, harder to maintain and depends on the libraries existing, working, etc. It's a total nightmare for portability and defeats the purpose of converting it to Go.
3. I want to avoid c2go becoming a huge suite of lots of different tools. It should be a first-class transpiler and do nothing else.
4. Let's not jump to conclusions about how it might work until we have a more clear understanding about why we want to do something like this, then discuss how it might work, then break it into much smaller pieces that can be incremented on.

**Comment by Konstantin8105** [comment]
Dear @elliotchance ,
Could you clarify your point 4 on example function `getopt` from `unistd.h`, this is very populary function in C for working with arguments flags.
Now, `c2go` haven't implementation of that function.

**Comment by elliotchance** [comment]
@Konstantin8105 I have specific goals for this project. I want to avoid anything that steps into C-land otherwise c2go will turn into a tool that works with C (there's a bunch of tools out there that already do this). I want to keep in focused on being a transpiler that completely separates the need for C libraries, so it can produce a standalone Go code.

Low-level functionality (most of which is provided by cstdlib) will have to be written in Go. Some of these are more complicated than others (like `getopt`) but I want to avoid the need to link to C libraries at all.

This discussion has extended past the original question, I'm closing it now.
