### ISSUE TITLE
Command-line flags

### ISSUE THREAD

**Issue by cristim** [elliotchance/c2go#74]
It would be nice to have some command-line flags to support multiple operations:

- -transpile: pretty much the current behavior, generates a .go source code for each C file passed as argument
- -run: transpile .c source code into Go and perform a run directly, just like done by the "go run" command in https://github.com/golang/go/blob/master/src/cmd/go/internal/run/run.go.
- -build: transpile C code myfile.c to Go and build it to generate a static binary called myfile, would also accept a -out parameter to be able to customize the binary name.

**Comment by elliotchance** [comment]
That makes sense. I would suggest that since these could be considered completely different modes of the CLI that they should perhaps not be flags, but rather a keyword like `go` or `git` do:

```bash
c2go transpile foo.c
c2go run foo.c
c2go build foo.c
```

**Comment by pravj** [comment]
Hi @elliotchance,

I second your comment to go with separate keywords instead of multiple flags in a single command.
Managing multiple flags will result in a serious problem given that the project has future scope of growing in terms of features.

If you allow, and if you aren't managing any blocking development, do you mind if I start working on it?

I think [cobra](https://github.com/spf13/cobra) is a suitable tool to develop command-line interactions, matching our requirements.
