### ISSUE TITLE
make/cmake integration example

### ISSUE THREAD

**Issue by jleni** [elliotchance/c2go#782]
Sorry for adding this as an issue but I was not sure how to ask this question:

Is it possible to use c2go as a replacement for gcc / clang in Make / CMake?

It would be great if you could add a simple example in the docs of a small project being built with c2go

**Comment by elliotchance** [comment]
The idea is that c2go would be a replacement for clang since it uses clang so heavily and produces output based on the clang AST. It's possible that it works with other flavours of CC (like GCC) but they are less tested.

c2go works for many simple programs but is no where near production quality where it can be simply dropped in. It's more just a proof of concept that C code can be transpiled to working Go code, but this usually this means that the developer has to clean up a few things and they should have a lot of testing to back it up.

It's far more likely that programs converted with c2go is a once off process (like migrating a math library or legacy CLI tool). I couldn't imagine why somebody would need to continue coding in C but have their build process constantly producing Go code.

This is a very long, round about way to answer your question. The README does actually contain an example of usage:

```bash
c2go transpile myfile.c
```

**Comment by jleni** [comment]
I understand it is definitely a one off process. The issue is that in many cases, the idea is to transpile a small project, there are makefiles (or any build system for that matter) that goes through a list of files, sets dependencies, include paths, etc.

The result will/may still need manual adjustments and that is fine.. it is actually amazing! But what I find inconvenient is to transpile file by file. That is why I was suggesting this.

**Comment by elliotchance** [comment]
I see. Well c2go does support transpiring multiple files but it doesn't work with one-to-one mechanics of how CC would do it by compiling object files then linking them later. There was a bit of discussion on this: https://github.com/elliotchance/c2go/issues/63

It's "less documented" because it doesn't work in all cases and we were trying to nail a proper solution (which I guess we never really got to) but you should be able to do:

```bash
c2go transpile file1.c file2.c
```
