### ISSUE TITLE
The name of a variable or field cannot be "type"

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#83]
`type` is a reserved word in Go so we not only have to replace it at the source of the declaration but also any time a variable or struct field is referenced.

**Comment by pravj** [comment]
The same goes for other keywords of Go those are absent in C. `SetKeywords(C) - SetKeywords(Go)`
We should check for these names and replace them.

Can confirm failing test cases when I replace `n` with these names in `prime.c`.

**Comment by pravj** [comment]
`SetKeywords(Go) - SetKeywords(C)`

- chan
- defer
- fallthrough
- func
- go
- import
- interface
- map
- package
- range
- select
- type
- var

Instead of [checking for each such name](https://github.com/elliotchance/c2go/blob/376cce8c0b1591543e441c4444beff66eb2d4ba3/transpiler/declarations.go#L29-L33), we can keep a map (map[string][bool]) of these names to verify if we should replace the field name.

**Comment by elliotchance** [comment]
I agree for a more generic solution and also that the hack that currently exists is not a valid solution.

I like the solution you suggested, would you be interested in putting in a PR for this?

**Comment by pravj** [comment]
Sure! I will implement it tomorrow.
