### ISSUE TITLE
Unions are not supported

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#84]

**Comment by corebreaker** [comment]
Hello,

I have really need to tanslate C union type, therefore i started to thinking about a solution and i find out 2 candidates:
- By using fields in a struct that alias on a same data (https://play.golang.org/p/CMudl2mRju),
- By a common type with getter et setter which cast the value (https://play.golang.org/p/JyiMBI3H2z)

I'd like to try to integrate the second solution in the _c2go_ project.

Plus, there is a problem with nested structure like this:
```C
struct T {
    int i;
    struct N {
        int j;
    } n;
};
```

The nested structure `N` is not processed. The problem is in the file _transpiler/declarations.go_ in the function _transpileRecordDecl_:
```go
func transpileRecordDecl(p *program.Program, n *ast.RecordDecl) error {
    // .................................
    var fields []*goast.Field
    for _, c := range n.Children {
        f, _ := transpileFieldDecl(p, c.(*ast.FieldDecl)) // <<-- Here c has type (*ast.RecordDecl) in these cases
        fields = append(fields, f)
    }
    // .................................

    return nil
}
````

**Comment by elliotchance** [comment]
Hi @corebreaker, I too ran into the issue you're referring to; which is not fixed but will raise a warning instead of stopping the compilation: https://github.com/elliotchance/c2go/pull/112/files#diff-e62d6474be0d5329ed6cdbb5558391ceR63. The nested structures should have their own issue raised so that bug can be fixed independently.

I agree the second solution is better and looks good to me. I'm looking forward to the PR.

Also remember we have a Gitter chat room if you want to chat or get faster responses to general questions :)

**Comment by corebreaker** [comment]
Ok, i took note.

**Comment by elliotchance** [comment]
@corebreaker did you have any luck with this?

**Comment by corebreaker** [comment]
Yes, i'm thinking that is a good beginning. I posted a pull request.

**Comment by corebreaker** [comment]
I applied modification by following your code review. I added some comment to explain my choices for few cases like `IsUnion` field or other changes in `program` package.
